### ISSUE TITLE
`@bind:after`

### ISSUE THREAD

**Issue by KristofferStrube** [alcedosoft/Blazor.Sqlite.FileSystemAccess#1]
Awesome project! Really creative combination of technologies and packages.

I see that you often use `@onchange` for your inputs on your sample pages instead of binding and I see it is because you have async effects on change. Try to take a look at `@bind:after` introduced in .NET 7. With that, you can asynchronous side effects after a bind set which would make your code somewhat simpler.

A small nitpick but it jumped out at me. Awesome job, once again.

**Comment by fixnil** [comment]
Thank you very much for your patience in pointing out this problem!

When I wrote this code, I felt very strange. Because I am not familiar with the topic of Blazor components, I can only search for the results I want from intellisense, but I cannot find them.

This is no small matter. We are also strict about the code, so this suggestion solves a very big problem for me.

I have tried your scheme and everything is normal! Thanks again for your advice! 👍
